const DEFAULT_HIDE_DELAY = 0;
const DEFAULT_SHOW = true;
const DEFAULT_SHOW_ARROW = true;
const DEFAULT_SHOW_DELAY = 0;

export { DEFAULT_HIDE_DELAY, DEFAULT_SHOW, DEFAULT_SHOW_ARROW, DEFAULT_SHOW_DELAY };
