const DEFAULT_MIN_HEIGHT = 240;
const DEFAULT_MIN_WIDTH = 320;
const DEFAULT_WIDTH = 512;
const MEDIA_QUERY = '(max-width: 640px)';

export { DEFAULT_MIN_HEIGHT, DEFAULT_MIN_WIDTH, DEFAULT_WIDTH, MEDIA_QUERY };
