const DEFAULT_ANIMATION_DURATION = 150;
const DEFAULT_HAS_ANIMATION = true;
const DEFAULT_IS_FULL_SCREEN = false;

export { DEFAULT_ANIMATION_DURATION, DEFAULT_HAS_ANIMATION, DEFAULT_IS_FULL_SCREEN };
