const DEFAULT_ANIMATION_DURATION = 150;
const DEFAULT_HAS_ANIMATION = true;
const DEFAULT_MAX_WIDTH = 512;
const DEFAULT_SHOW_CLOSE_BUTTON = true;
const DEFAULT_SHOW_FULL_SCREEN_BUTTON = true;
const DEFAULT_SHOW_TOOLTIPS = true;

export {
  DEFAULT_ANIMATION_DURATION,
  DEFAULT_HAS_ANIMATION,
  DEFAULT_MAX_WIDTH,
  DEFAULT_SHOW_CLOSE_BUTTON,
  DEFAULT_SHOW_FULL_SCREEN_BUTTON,
  DEFAULT_SHOW_TOOLTIPS,
};
