const DEFAULT_ANIMATION_ACTIVE = true;
const DEFAULT_ANIMATION_DURATION = 150;
const DEFAULT_ANIMATION_TYPE = 'ease-in-out';
const EXCLUDED_PROPS = ['animation', 'opacity', 'open'];

export {
  DEFAULT_ANIMATION_ACTIVE,
  DEFAULT_ANIMATION_DURATION,
  DEFAULT_ANIMATION_TYPE,
  EXCLUDED_PROPS,
};
